cross-platform tests
inscopix/py_isx pull request #49
Opened 2024-02-02 23:36 UTC by bendichter

2024-02-13 21:18 UTC, nosheen-adil requested changes

2024-02-13 21:18 UTC, nosheen-adil commented on .github/workflows/main.yml
> +          shell: bash  # Ensure using bash for cross-platform compatibility, especially on Windows
@bendichter Looks like the pr checks are failing due to this line. Should look like this instead:
```
shell: bash
run: |
          pip install -e .[test]
          make test-pip
```

2024-02-15 14:51 UTC, nosheen-adil approved these changes
@bendichter Thanks for the fix! LGTM

2024-02-15 15:20 UTC, nosheen-adil commented
@bendichter Something unusual is happening with the github checks. All the pre merge checks passed, but it still says some checks haven't completed yet, so the PR can't be merged.

I tried re-running the github checks, but no change. Can you push an empty commit to this branch? Maybe that will properly retrigger the checks.

2024-02-15 15:23 UTC, CodyCBakerPhD commented
@nosheen-adil this tends to happen when the merge requirements set on the admin side have a mismatch in name - which will happen on this PR since the name of the platform is now shown

You'll probably have to update the branch requirements to match the way they look on this PR (if they show up at all - they may have to first be run on the main fork rather than an outside one), and remove the previous names as requirements

2024-02-20 18:51 UTC, merged