Add PR template
inscopix/py_isx pull request #50
Opened 2024-02-13 21:30 UTC by nosheen-adil

## Description 
Add a PR template to improve the review process for open source contributions.

2024-02-13 21:56 UTC, JohannCooper requested changes
Thanks for making this! 

Just a few suggestions, open to other opinions.

2024-02-13 21:56 UTC, JohannCooper commented on .github/pull_request_template.md
> +## Related Tickets & Documents
```suggestion
## Related Issues & Documents
```
To match the GitHub vocabulary and wording used below.

2024-02-13 21:56 UTC, JohannCooper commented on .github/pull_request_template.md
> +## Description
```suggestion
## Description

_Please provide a brief description of the changes introduced by this pull
request._
```

Might be good to have a prompt here as well.

2024-02-13 21:56 UTC, JohannCooper commented on .github/pull_request_template.md
> +_We encourage you to write unit tests when possible._
```suggestion
<!-- We encourage you to write unit tests when possible. -->
```
Maybe we change this to a comment so contributors still see it when filling out the template but it doesn't appear when published. It also seems like the convention established here is that italic text should be replaced. This line isn't necessarily something to be replaced.

2024-02-13 22:11 UTC, Zachary-Ip approved these changes
Thanks for adding this!

2024-02-15 16:36 UTC, JohannCooper approved these changes
Looks great!

2024-02-20 17:30 UTC, merged